project:
  type: website
  output-dir: docs

website:
  title: "Mehmet Göktuğ Öztürk"
  site-url: "https://mehmetgoktug.github.io/"
  description: "Mehmet Göktuğ Öztürk is an ecologist and geospatial analyst working on GIS, remote sensing, spatial analysis, fire ecology, ecological modelling, and biogeography."
  favicon: "favicon.webp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://r-delisi.github.io/
        text: Blog
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - sandstone
    mainfont: Inter
    css: styles.css
    toc: true



