project:
  type: website
  output-dir: docs

website:
  title: "Mehmet Göktuğ Öztürk"
  description: "Mehmet Göktuğ Öztürk"
  favicon: "favicon.webp"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://r-delisi.github.io/
        text: Blog
      - href: publications.qmd
        text: Publications

format:
  html:
    theme:
      - sandstone
    mainfont: Inter
    css: styles.css
    toc: true



